/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#dae5e0",
        "surface-container-low": "#141d1b",
        "on-tertiary-container": "#00704d",
        "surface-tint": "#00e479",
        "on-surface": "#dae5e0",
        "on-primary-fixed-variant": "#005228",
        "inverse-on-surface": "#293230",
        "outline-variant": "#3b4b3d",
        "primary-fixed-dim": "#00e479",
        "on-secondary-container": "#00424e",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004e5c",
        "surface-container-high": "#222c29",
        "on-secondary": "#003640",
        "surface-container-highest": "#2d3734",
        "background": "#0c1513",
        "on-tertiary-fixed-variant": "#005137",
        "outline": "#849585",
        "secondary-fixed-dim": "#4cd7f6",
        "tertiary": "#eefff3",
        "tertiary-fixed": "#85f8c4",
        "tertiary-fixed-dim": "#68dba9",
        "error": "#ffb4ab",
        "secondary-fixed": "#acedff",
        "on-primary": "#003919",
        "surface-container": "#18211f",
        "on-primary-container": "#007139",
        "secondary-container": "#03b5d3",
        "surface-dim": "#0c1513",
        "inverse-surface": "#dae5e0",
        "surface-container-lowest": "#07100e",
        "primary-fixed": "#60ff99",
        "tertiary-container": "#81f4c0",
        "primary": "#f1ffef",
        "surface": "#0c1513",
        "on-surface-variant": "#b9cbb9",
        "on-primary-fixed": "#00210c",
        "surface-variant": "#2d3734",
        "surface-bright": "#323b38",
        "primary-container": "#00ff88",
        "on-tertiary-fixed": "#002114",
        "inverse-primary": "#006d37",
        "on-tertiary": "#003825",
        "on-error": "#690005",
        "secondary": "#4cd7f6",
        "error-container": "#93000a",
        "on-secondary-fixed": "#001f26",
        // Extended obsidian palette
        "obsidian-deep": "#020605",
        "obsidian-card": "rgba(3,10,8,0.78)",
        "emerald-neon": "#00ff88",
        "cyan-telemetry": "#06b6d4",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-lg": "2rem",
        "space-xs": "0.25rem",
        "gutter": "1.5rem",
        "margin": "2rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "gutter-sm": "1rem",
        "margin-lg": "4rem",
        "margin-sm": "1rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "body-sm": ["Geist", "system-ui", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "label-hud": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "label-xs": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Geist", "system-ui", "sans-serif"],
        "body-md": ["Geist", "system-ui", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "sans": ["Geist", "system-ui", "sans-serif"],
        "heading": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "label-hud": ["11px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "label-code": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "label-xs": ["9px", { "lineHeight": "12px", "letterSpacing": "0.12em", "fontWeight": "500" }],
        "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }]
      },
      boxShadow: {
        'emerald-sm': '0 0 12px rgba(0, 255, 136, 0.15)',
        'emerald-md': '0 0 24px rgba(0, 255, 136, 0.25)',
        'emerald-lg': '0 0 40px rgba(0, 255, 136, 0.35)',
        'cyan-sm': '0 0 12px rgba(76, 215, 246, 0.2)',
        'cyan-md': '0 0 24px rgba(76, 215, 246, 0.3)',
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'dash-move': 'dashMove 15s linear infinite',
      },
      keyframes: {
        dashMove: {
          '0%': { strokeDashoffset: '0' },
          '100%': { strokeDashoffset: '100' },
        }
      }
    }
  },
  plugins: [],
}
